---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: update_cache=yes upgrade=yes
      become: yes

    - name: Install avahi for multicast DNS/DNS-SD service discovery
      apt: pkg=avahi-daemon
      become: yes

  roles:
    - plantuml
    - git
    - vim
    - python
    - ansible
    - docker
    - packer
    - ruby
    - libmagick

  post_tasks:
    - name: Add docker group for user
      user: name=vagrant groups=docker append=yes
      become: yes

    - name: Set python3 as default python
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3
      become: yes
