---
- hosts: all

  roles:
    - git
    - python
    - ansible
    - docker
    - packer
    - ruby

  post_tasks:
    - name: Set python3 as default python
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3
      become: yes
